[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-chatbot-mental-health"
version = "0.1.0"
description = "MSc AI Final Year Project: AI Chatbot for Mental Health"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "UDIT" }
]

[tool.setuptools.packages.find]
where = ["."]

[tool.pyright]
extraPaths = [".", "src"]
